### ISSUE TITLE
请问要怎么初始化工程

### ISSUE THREAD

**Issue by sunzeboy** [waylybaye/XcodeCleaner#1]
打开工程运行报错，提示React相关的库找不到

**Comment by guyuekk** [comment]
同样遇到这个问题

**Comment by 577528249** [comment]
应该是在用终端cd到项目目录下运行npm install命令吧，安装那些依赖，但是安装好了之后还是报其他的错，
Ld /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release/XcodeCleaner.app/Contents/PlugIns/XcodeCleanerTests.xctest/Contents/MacOS/XcodeCleanerTests normal x86_64
    cd /Users/ruiwendaier/Downloads/XcodeCleaner-master/macos
    export MACOSX_DEPLOYMENT_TARGET=10.13
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release -F/Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Intermediates.noindex/XcodeCleaner.build/Release/XcodeCleanerTests.build/Objects-normal/x86_64/XcodeCleanerTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mmacosx-version-min=10.13 -bundle_loader /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release/XcodeCleaner.app/Contents/MacOS/XcodeCleaner -Xlinker -object_path_lto -Xlinker /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Intermediates.noindex/XcodeCleaner.build/Release/XcodeCleanerTests.build/Objects-normal/x86_64/XcodeCleanerTests_lto.o -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -framework XCTest /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release/libReact.a -Xlinker -dependency_info -Xlinker /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Intermediates.noindex/XcodeCleaner.build/Release/XcodeCleanerTests.build/Objects-normal/x86_64/XcodeCleanerTests_dependency_info.dat -o /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release/XcodeCleaner.app/Contents/PlugIns/XcodeCleanerTests.xctest/Contents/MacOS/XcodeCleanerTests

ld: file not found: /Users/ruiwendaier/Library/Developer/Xcode/DerivedData/XcodeCleaner-gvegtztvqqufyedbhyxxecxaygwy/Build/Products/Release/XcodeCleaner.app/Contents/MacOS/XcodeCleaner
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by waylybaye** [comment]
我在 README 里面加上 Build 的步骤了，可以试下

**Comment by CHPisces** [comment]
请问现在提示，folly/portability/config.h file not found  怎么处理

**Comment by waylybaye** [comment]
你看看log是不是有文件下载失败了，初始化过程需要科学上网否则可能会下载失败。

**Comment by yc913344706** [comment]
npm install是不是要先在mac上安装npm，现在安装不上。。。SOS

**Comment by CoderAndCat** [comment]
<img width="570" alt="2017-10-14 17 03 33" src="https://user-images.githubusercontent.com/22518690/31574404-bb949d80-b101-11e7-8a09-5e71a60ad95a.png">
报错了

**Comment by CHPisces** [comment]
我的提示找不到这两个库，手动下载
folly-2016.09.26.00  https://github.com/facebook/folly/releases/tag/v2016.09.26.00
boost_1_63_0 https://sourceforge.net/projects/boost/files/boost/1.63.0/

XcodeCleaner/node_modules/react-native-macos中替换成功运行

**Comment by 0xdatou** [comment]
@CHPisces +1
