### ISSUE TITLE
运行成功但是没有内容

### ISSUE THREAD

**Issue by gdfyj90** [waylybaye/XcodeCleaner#16]
![image](https://user-images.githubusercontent.com/6669427/32642078-832f6f06-c597-11e7-99ae-14838a463e8f.png)
一片空白

**Comment by xingfuqiu** [comment]
me too

**Comment by WangJiaLe1027** [comment]
Disable App Sandbox in target's Capabilities.
在Capabilities里把sandbox改成off状态 @xingfuqiu @gdfyj90

**Comment by xingfuqiu** [comment]
是改过的, Terminal 报错
<img width="565" alt="2017-11-13 16 01 37" src="https://user-images.githubusercontent.com/391606/32715149-018a2584-c88c-11e7-8b25-f7b6fa111143.png">

**Comment by waylybaye** [comment]
遇到问题最好先看一下已有的 Issue #9

**Comment by xingfuqiu** [comment]
@waylybaye 感谢,已正常运行
