### ISSUE TITLE
building的时候报这个错 在终端里

### ISSUE THREAD

**Issue by CoderAndCat** [waylybaye/XcodeCleaner#3]
Looking for JS files in
   /Users/macbookpro/Desktop/XcodeCleaner-master
   /Users/macbookpro/Desktop/XcodeCleaner-master/node_modules/react-native-macos/packager 

React packager ready.

Loading dependency graph, done.
2017-10-15 10:28 node[76329] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-15 10:28 node[76329] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1021:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1360:9)
~
Process terminated. Press <enter> to close the window

**Comment by waylybaye** [comment]
你试试最新的代码和Build步骤

**Comment by waylybaye** [comment]
或者参考下这个链接 https://github.com/facebook/react-native/issues/10028

我建议升级下 watchman 试试

**Comment by CoderAndCat** [comment]
disable App Sandbox in target's Capabilities  这一步是啥意思 没明白  /胆怯

**Comment by CoderAndCat** [comment]
<img width="583" alt="2017-10-15 11 21 02" src="https://user-images.githubusercontent.com/22518690/31581307-0205a6e4-b19b-11e7-9c72-1f233a421686.png">
到这里是不是要科学上网，

**Comment by waylybaye** [comment]
这都已经正常运行了
