### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by CHPisces** [waylybaye/XcodeCleaner#5]
当初设置管理员账户名称和我的文件夹名称不对应，会授权失败，当然这个是我自己的问题，不过想找个解决方案……

**Comment by waylybaye** [comment]
你改下index.js 165行代码，自己先写死下吧……或者 `ln -s` 建个软连接？

**Comment by waylybaye** [comment]
不对，我好像应该用打开框选择的目录来作为developer 目录这样就可以手动选目录了……

**Comment by CHPisces** [comment]
是有选择目录框，但是因为用户名和文件夹名不对应，所以和你预设应授权的文件夹是不符的，改index.macos.js是有效的，谢谢！
